name: issue801

on:
 workflow_dispatch:
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
 testjob:
    name: pip
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Verify PNPM Cache Directory
        run: |
          if [ ! -d "$PNPM_CACHE_FOLDER/store/v3" ]; then
            echo "PNPM cache directory does not exist, creating it."
            mkdir -p "$PNPM_CACHE_FOLDER/store/v3"
          else
            echo "PNPM cache directory exists."
          fi
      - uses: actions/setup-node@v4
        with:
           node-version: '18'
           cache: 'pnpm'
           cache-dependency-path: '**/pnpm-lock.yaml'
