name: MirrorUrl-1240PR

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
        node-version: [ '20.0.0-v8-canary', '20-v8-canary', 'v21.0.0-v8-canary20230514490c2e93ba'] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: marco-ippolito/setup-node@mirror
        with:
          node-version: ${{ matrix.node-version }}
          mirror: 'https://nodejs.org/download/v8-canary'
          mirror-token: ${{secrets.GITHUB_TOKEN}}
      - name: Verify Node.js installation
        run: node -v  
