name: mirrorurl-pr1240

on:
 workflow_dispatch:
 

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-24.04-arm]
        node-version: [23]  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: marco-ippolito/setup-node@mirror
        with:
          node-version: ${{ matrix.node-version }}

      - name: Verify Node.js Installation
        run: |
          node -v
          npm -v
