name: withMirrorUrl

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: marco-ippolito/setup-node@mirror
        with:
          node-version: '22'
          mirror: 'https://nodejs.org/download/release/'
          mirror-token: ${{secrets.TOKEN_GITHUB}}
      - name: Verify Node.js installation
        run: node -v  
