name: MirrorUrl-1240PR

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: marco-ippolito/setup-node@mirror
        with:
          node-version-file: '.nvmrc'
          mirror: 'https://nodejs.org/ '
          mirror-token: ${{secrets.GITHUB_TOKEN}}
          check-latest: true
      - name: Verify Node.js installation
        run: node -v 
