name: MirrorUrl-1240PR

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
        node-version: [lts/erbium, lts/fermium, lts/*, lts/-n] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: marco-ippolito/setup-node@mirror
        with:
          node-version: ${{ matrix.node-version }}
          mirror: 'https://mirror.yandex.ru/mirrors/nodejs.org/'
          mirror-token: ${{secrets.GITHUB_TOKEN}}
          check-latest: true
      - name: Verify Node.js installation
        run: node -v  
